services:
  ollama-web-dev:
    build:
      context: ..
      dockerfile: ./Dockerfile
    volumes:
      # Mount the workspace folder
      - ..:/workspaces:cached
    environment:
      - NODE_ENV=development
      - PORT=8080
      - OLLAMA_URL=${OLLAMA_URL:-http://host.docker.internal:11434}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
